org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

loader_version=0.19.3
loom_version=1.17-SNAPSHOT
mpp_version=2.0.0

mod_version=2.0.0
mod_name=Deepslate Dungeons
mod_id=deepslate-dungeons
mod_description=Builds dungeons and strongholds below y = 0 out of deepslate instead of stone!

update_name_suffix=
maven_group=com.axialeaa

target_version=~26.2
build_version=26.2
modrinth_versions=26.2
fabric_api_version=0.152.1+26.2

modmenu_version=20.0.0-beta.2

modrinth_project_id=2niNeF0R
repository_url=axialeaa/DeepslateDungeons